version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: "admin"
      POSTGRES_DB: "clojure-postgres"